# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac87d198ad103149065dfea08be1f656c376420c503ca8d23d84e09daf7a93c726f9b16cd9f2ccb7fdc0d798dbe56d0faff0adc32e65a39514c09c9afa2ed07

test:
  secret_key_base: 92ae205c15eb18d7fdbbcbf02e7f3cfd29daf475b168442da1948ffc620f333d7e04c9be78b9fc6bdd5412eb25be8c5123ac23f77ebb24e8f1480886aa92c5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
